# Generated by Django 4.2.23 on 2026-03-13 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryterm',
            options={'ordering': ['term']},
        ),
        migrations.RemoveField(
            model_name='lecturesession',
            name='is_active',
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='sign_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='subject_area',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('live', 'Live'), ('ended', 'Ended')], default='waiting', max_length=10),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='has_technical_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='seconds_from_start',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='caption_language',
            field=models.CharField(blank=True, default='en-US', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dyslexia_font',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_mode',
            field=models.CharField(blank=True, choices=[('caption', 'Smart Captions'), ('audio', 'Audio Description'), ('sign', 'Sign Language')], default='caption', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='SessionSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='slides/')),
                ('ai_description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='core.lecturesession')),
            ],
            options={
                'ordering': ['slide_number'],
                'unique_together': {('session', 'slide_number')},
            },
        ),
    ]
