# Generated by Django 4.2.23 on 2026-03-13 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_glossaryterm_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('fill_blank', 'Fill in the Blank'), ('definition', 'Definition Match'), ('true_false', 'True or False')], max_length=20)),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('hint', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='core.lecturesession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LectureSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('detected_terms', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.lecturesession')),
            ],
        ),
        migrations.CreateModel(
            name='LectureAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_words', models.IntegerField(default=0)),
                ('total_sentences', models.IntegerField(default=0)),
                ('unique_words', models.IntegerField(default=0)),
                ('avg_wpm', models.FloatField(default=0)),
                ('complexity_score', models.FloatField(default=0)),
                ('complexity_label', models.CharField(default='', max_length=20)),
                ('reading_ease', models.FloatField(default=0)),
                ('grade_level', models.FloatField(default=0)),
                ('topic_segments', models.JSONField(default=list)),
                ('wpm_timeline', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.lecturesession')),
            ],
        ),
    ]
